name: coingecko_api
description: Dart package that provides simple access to the CoinGecko API (Version 3)
version: 1.0.0+3
repository: https://github.com/yegor-pelykh/coingecko_api
issue_tracker: https://github.com/yegor-pelykh/coingecko_api/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  intl: ^0.17.0
  test: ^1.17.12
